### ISSUE TITLE
Demo- UI issues checklist

### ISSUE THREAD

**Issue by LiamOSullivan** [BuildingCityDashboards/bcd-dd-v2.1#1490]
Queries

- [x] Add Query card for PPR

- [ ] Need the travel map for example of real-time data

- [ ] Add planning tool as a placeholder

Home

- [ ] short gradient showing at bottom of hero image

- [x] Date, time right hand padding should account for scrollbar

- [x] #673 

Themes

- [ ] traffic counters popup - needed as example of map for demo

GeoDemos

- [ ] Add title

- [ ] Style popup
